ALTER PROCEDURE [dbo].[SP_PAYASUGO_GET_TX_DETAILS]
		@TRANSACTION_REF_NUM VARCHAR(50), @SITE_NAME VARCHAR(50)	
AS	
BEGIN
DECLARE @SQL NVARCHAR(MAX) = '';
DECLARE @CONDITION NVARCHAR(MAX) = '';
SET @SQL = ' SELECT
             payasugoTx.ID AS pasAsUGoTx_ID
            ,payasugoTx.TX_REFERENCE_NUM AS pasAsUGoTx_TX_REFERENCE_NUM
            ,payasugoTx.ORG_REF_NUM AS pasAsUGoTx_ORG_REF_NUM
            ,payasugoTx.AMOUNT AS pasAsUGoTx_AMOUNT
            ,payasugoTx.SERVICE_FEE AS pasAsUGoTx_SERVICE_FEE
            ,payasugoTx.TX_AMOUNT AS pasAsUGoTx_TX_AMOUNT
            ,payasugoTx.COMMENTS AS pasAsUGoTx_COMMENTS
            ,payasugoTx.TX_TYPE AS pasAsUGoTx_TX_TYPE
            ,payasugoTx.CHECKNUM AS pasAsUGoTx_CHECKNUM
            ,payasugoTx.TX_DATE AS pasAsUGoTx_TX_DATE  	                    
            ,payasugoTx.CARD_NUMBER AS pasAsUGoTx_CARD_NUMBER
            ,payasugoTx.ACCOUNTNAME AS pasAsUGoTx_ACCOUNTNAME
            ,payasugoTx.MACHINENAME AS pasAsUGoTx_MACHINENAME
            ,payasugoTx.DATE_TIME_CREATED AS pasAsUGoTx_DATE_TIME_CREATED
            ,payasugoTx.SETTLEMENT_STATUS AS pasAsUGoTx_SETTLEMENT_STATUS
            ,site.NAME AS site_NAME
			,users.EMAIL_ID AS users_EMAIL_ID
            ,access.ACCESS_DESCR AS access_ACCESS_DESCR
            ,ACCESS.ID AS ACCESS_ID
            ,merchant.PARTNER AS merchant_PARTNER
            ,merchant.VENDORNAME AS merchant_VENDORNAME
            ,merchant.USERNAME AS merchant_USERNAME
            ,merchant.PASSWORD AS merchant_PASSWORD           
            ,payasugoTx.USER_ID AS pasAsUGoTx_USER_ID
            ,payAsUGoTxItems.ID AS pasAsUGoTxItems_ID
            ,payAsUGoTxItems.PRODUCT_ID AS pasAsUGoTxItems_PRODUCT_ID
			,payAsUGoTxItems.PRODUCT_TYPE AS pasAsUGoTxItems_PRODUCT_TYPE
			,payAsUGoTxItems.PAGE_COUNT AS pasAsUGoTxItems_PAGE_COUNT
			,payAsUGoTxItems.AMOUNT AS pasAsUGoTxItems_AMOUNT
			,payAsUGoTxItems.SERVICE_FEE AS pasAsUGoTxItems_SERVICE_FEE
			,payAsUGoTxItems.TOTAL_AMOUNT AS pasAsUGoTxItems_TOTAL_AMOUNT
			,payAsUGoTxItems.IS_REFUNDED	AS pasAsUGoTxItems_IS_REFUNDED
			,payAsUGoTxItems.DATE_TIME_MOD AS pasAsUGoTxItems_DATE_TIME_MOD
			,payAsUGoTxItems.DOWNLOAD_URL AS pasAsUGoTxItems_DOWNLOAD_URL
			,payAsUGoTxItems.COMMENTS AS ITEMCOMMENTS
			,merchant.ID AS merchant_ID
			,payAsUGoTxItems.IS_DOCUMENT_AVAILABLE AS pasAsUGoTxItems_IS_DOCUMENT_AVAILABLE
			,payasugoTx.MOD_USER_ID AS pasAsUGoTx_MOD_USER_ID
			,site.ID AS site_ID
			,merchant.TRAN_FEE_PERCENTAGE AS merchant_TRAN_FEE_PERCENTAGE
            ,merchant.TRAN_FEE_FLAT AS merchant_TRAN_FEE_FLAT
            ,payasugoTx.CARD_TYPE AS pasAsUGoTx_CARD_TYPE
            ,merchant.TRAN_FEE_PERCENTAGE_AMEX AS merchant_TRAN_FEE_PERCENTAGE_AMEX
            ,merchant.TRAN_FEE_FLAT_AMEX AS merchant_TRAN_FEE_FLAT_AMEX
            ,site.DESCRIPTION AS site_DESCRIPTION
            ,payasugoTx.TRAN_FEE_PERCENTAGE AS pasAsUGoTX_TRAN_FEE_PERCENTAGE
            ,payasugoTx.TRAN_FEE_FLAT AS pasAsUGoTX_TRAN_FEE_FLAT
            ,payasugoTx.CREATED_BY AS pasAsUGoTx_CREATED_BY
            ,payAsUGoTxItems.DATE_TIME_CREATED AS pasAsUGoTxItems_DATE_TIME_CREATED
            ,site.TIMEZONE
			,ISNULL(LOCATION.[DESCRIPTION], ''N/A'') AS LOCATION_NAME
			,payasugoTx.FIRM_ADMIN_USER_ACCESS_ID AS FIRM_ADMIN_USER_ACCESS_ID
			,payasugoTx.IS_CERTIFIED
			,payAsUGoTxItems.CERTIFIED_DOCUMENT_NUMBER
			,ISNULL(payasugoTx.PAGE_COUNT, 1) AS PAYASUGOTX_PAGE_COUNT
			,ISNULL(payasugoTx.ITEM_COUNT, 1) AS PAYASUGOTX_ITEM_COUNT
			,payAsUGoTxItems.ITEM_NAME AS pasAsUGoTxItems_ITEM_NAME
			,MERCHANT.IS_MICROPAYMENT_ACCOUNT AS  merchant_IS_MICROPAYMENT_ACCOUNT
			,CREDITUSAGE_FEE.TX_FEE_FLAT AS CREDITUSAGE_FEE_TX_FEE_FLAT
			,CREDITUSAGE_FEE.TX_FLAT_FEE_CUTOFF_AMT AS CREDITUSAGE_FEE_TX_FLAT_FEE_CUTOFF_AMT
			,CREDITUSAGE_FEE.TX_FEE_PERCENT AS CREDITUSAGE_FEE_TX_FEE_PERCENT
			,CREDITUSAGE_FEE.DOWNGRADE_FEE AS CREDITUSAGE_FEE_DOWNGRADE_FEE 
			,CREDITUSAGE_FEE.TX_FEE_ADDITIONAL AS CREDITUSAGE_FEE_TX_FEE_ADDITIONAL 
			,CREDITUSAGE_FEE.MICRO_TX_CUT_OFF AS CREDITUSAGE_FEE_MICRO_TX_CUT_OFF
			,SITE.ENABLE_MICRO_TX_WEB AS site_ENABLE_MICRO_TX_WEB
			,SITE.ENABLE_MICRO_TX_OTC AS site_ENABLE_MICRO_TX_OTC 
      FROM
            ECOMM_PAYASUGO_TX PAYASUGOTX
            INNER JOIN ECOMM_PAYASUGO_TX_ITEMS payAsUGoTxItems ON (payAsUGoTxItems.PAYASUGO_TX_ID = payasugoTx.ID OR payasugoTx.ID = payAsUGoTxItems.REFUND_TRAN_ID)
            LEFT OUTER JOIN AUTH_USERS USERS ON payasugoTx.USER_ID = USERS.ID
            LEFT OUTER JOIN AUTH_ACCESS ACCESS ON ACCESS.ID = PAYASUGOTX.ACCESS_ID
            INNER JOIN ECOMM_SITE SITE ON SITE.ID = payasugoTx.SITE_ID        
            INNER JOIN ECOMM_MERCHANTINFO MERCHANT on MERCHANT.SITE_ID = SITE.ID	
			LEFT OUTER JOIN ECOMM_LOCATION LOCATION ON LOCATION.ID = payAsUGoTxItems.LOCATION_ID
			INNER JOIN ECOMM_CREDITUSAGE_FEE CREDITUSAGE_FEE on CREDITUSAGE_FEE.SITE_ID = site.ID
	WHERE (1=1) AND MERCHANT.ID = payasugoTx.MERCHANT_ID'

SET @CONDITION = @CONDITION + ' AND payasugoTx.TX_REFERENCE_NUM = ''' + @TRANSACTION_REF_NUM + ''''
IF (@SITE_NAME IS NOT NULL AND @SITE_NAME <> '')
SET @CONDITION = @CONDITION + ' AND SITE.NAME = ''' + @SITE_NAME + ''''
SET @SQL = @SQL + @CONDITION
--PRINT @SQL
EXECUTE SP_EXECUTESQL @SQL
END



GO


