/****** Object:  StoredProcedure [dbo].[SP_USER_GET_ALL_SUBSCRIPTIONS]    Script Date: 9/14/2015 12:19:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE  [dbo].[SP_USER_GET_ALL_SUBSCRIPTIONS]
	@USERNAME VARCHAR(50),
	@REGISTEREDNODE VARCHAR(50),
	@CURRENTSITE VARCHAR(50),
	@ACTIVEUBSCRIPTIONSONLY VARCHAR(1),
	@ADMINSUBSCRIPTIONONLY VARCHAR(1)
AS 
BEGIN
DECLARE @SQL NVARCHAR(4000) = '';
DECLARE @CONDITION NVARCHAR(4000) = '';
SET @SQL = 'SELECT      
      ESA.SITE_ID  AS ESA_SITE_ID,
      (SELECT SITE1.DESCRIPTION FROM ECOMM_SITE SITE1 WHERE SITE1.ID = ESA.SITE_ID) AS SITE1_DESCRIPTION,                  
      AA.ACCESS_DESCR AS AA_ACCESS_DESCR,
      (ISNULL(ESF.FEE,0)) AS ESF_Fee,       
      CASE
      WHEN LOOKUP.CATEGORY = ''RECURRING_SUBSCRIPTION''
		THEN CASE EUA.ACTIVE
			 WHEN  ''Y'' 
				THEN ''N''
			 ELSE CASE AUA.IS_ACCESS_OVERRIDDEN
					WHEN ''Y''
						THEN ''N''
					ELSE 
						''Y''
				END
			 END	
	  ELSE ''N''
      END             
       AS PaymentPending,
      EUA.LAST_BILLING_DATE AS EUA_LastBillingDate,
      EUA.NEXT_BILLING_DATE AS EUA_NextBillingDate,
      EUA.ID AS EUA_ACCOUNTID,
      AUA.ID AS AUA_USERACCESSID,
      AA.ID AS AA_ACCESSID,
      LOOKUP.CATEGORY AS LOOKUP_CATEGORY,
      EUA.MARK_FOR_CANCELLATION AS EUA_MARK_FOR_CANCELLATION,      
      AUA.DATE_TIME_MOD AS AUA_DATE_TIME_MOD,
      AUA.DATE_TIME_CREATED AS AUA_DATE_TIME_CREATED,
      AUA.MOD_USER_ID AS AUA_MOD_USER_ID,
      AUA.ACTIVE AS AUA_ACTIVE,
      AUA.COMMENTS AS AUA_COMMENTS,
      AUA.IS_ACCESS_OVERRIDDEN AS AUA_IS_ACCESS_OVERRIDDEN,
      AA.IS_AUTHORIZATION_REQUIRED AS AA_IS_AUTHORIZATION_REQUIRED,
      AUA.IS_AUTHORIZED AS AUA_IS_AUTHORIZED,
      ISNULL(EUA.CREATED_BY,AUA.CREATED_BY) AS ISNULL_CREATED_BY,
      EUA.DATE_TIME_MOD AS EUA_DATE_TIME_MOD,
      AUA.AUTHORIZED_DATETIME AS AUA_AUTHORIZED_DATETIME,
	  AUA.AUTHORIZED_BY AS AUA_AUTHORIZED_BY ,
	  AUA.IS_FIRM_ACCESS_ADMIN AS IS_FIRM_ACCESS_ADMIN,
	  AA.IS_FIRM_LEVEL_ACCESS AS IS_FIRM_LEVEL_ACCESS,
	  AA.MAX_USERS_ALLOWED AS MAX_USERS_ALLOWED,
	  AUA.FIRM_ADMIN_USER_ACCESS_ID AS AUA_FIRM_ADMIN_USER_ACCESS_ID,
	  AA.IS_GOVERNMENT_ACCESS AS IS_GOVERNMENT_ACCESS,
  	  AA.MAX_DOCUMENTS_ALLOWED AS MAX_DOCUMENTS_ALLOWED,
	  (SELECT AU1.FIRM_NAME  FROM AUTH_USERS AU1 INNER JOIN AUTH_USERS_ACCESS AUA1 ON AU1.ID = AUA1.USER_ID AND AUA1.ID = AUA.FIRM_ADMIN_USER_ACCESS_ID) AS SUB_ADMIN_FIRM_NAME,
	  AUA.OVERRIDDEN_UNTILL_DATE AS SUB_OVERRIDDEN_UNTILL_DATE
FROM
	  AUTH_USERS AU
	  INNER JOIN AUTH_USERS_ACCESS AUA ON AUA.USER_ID = AU.ID
      INNER JOIN AUTH_ACCESS AA ON AUA.ACCESS_ID = AA.ID
      LEFT OUTER JOIN ECOMM_USERS_ACCOUNT EUA ON EUA.USER_ACCESS_ID = AUA.ID
      INNER JOIN ECOMM_SITE_ACCESS ESA ON ESA.ACCESS_ID = AA.ID
      INNER JOIN ECOMM_SITE SITE ON ESA.SITE_ID = SITE.ID
      INNER JOIN ECOMM_NODE NODE ON NODE.ID = SITE.NODE_ID
      INNER JOIN ECOMM_SUBSCRIPTIONFEE ESF ON ESF.SITEACCESS_ID = ESA.ID
      INNER JOIN CODELOOKUP LOOKUP ON LOOKUP.ID = ESF.SUBSCRIPTION_TYP_ID WHERE AUA.IS_DELETED = ''N'''
SET @CONDITION = @CONDITION + 'AND AA.ACTIVE = ''Y'' AND ESA.ACTIVE = ''Y'' AND ESF.ACTIVE = ''Y'' AND LOOKUP.ACTIVE = ''Y'' '
IF (@USERNAME IS NOT NULL AND @USERNAME <> '')
SET @CONDITION = @CONDITION + ' AND AU.EMAIL_ID = ''' + @USERNAME + ''''
IF (@REGISTEREDNODE IS NOT NULL AND @REGISTEREDNODE <> '')
SET @CONDITION = @CONDITION + ' AND NODE.NAME = ''' + @REGISTEREDNODE + ''''
IF (@CURRENTSITE IS NOT NULL AND @CURRENTSITE <> '')
SET @CONDITION = @CONDITION + ' AND SITE.NAME = ''' + @CURRENTSITE + ''''
IF (@ACTIVEUBSCRIPTIONSONLY  IS NOT NULL AND @ACTIVEUBSCRIPTIONSONLY  <> '' AND @ACTIVEUBSCRIPTIONSONLY  <> 'N' )
SET @CONDITION = @CONDITION + ' AND AUA.ACTIVE = ''' + @ACTIVEUBSCRIPTIONSONLY + ''''
 
IF (@ADMINSUBSCRIPTIONONLY  IS NOT NULL AND @ADMINSUBSCRIPTIONONLY  <> '' AND @ADMINSUBSCRIPTIONONLY  <> 'N' )
SET @CONDITION = @CONDITION + ' AND AUA.IS_FIRM_ACCESS_ADMIN = ''' + @ADMINSUBSCRIPTIONONLY + ''''
SET @SQL = @SQL + @CONDITION
EXECUTE SP_EXECUTESQL @SQL
END

GO


