language: java
before_install: ant init-xmltask
script: ant buildwar
jdk:
  - oraclejdk8
env:
  global:
    - ARTIFACTS_KEY=AKIAJF225RQRARLOD63Q
    - ARTIFACTS_SECRET=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
    - ARTIFACTS_BUCKET=granicus-development-builds
    - ARTIFACTS_TARGET_PATHS="eaccept-ecom/$TRAVIS_COMMIT"
  matrix:
    - ENV_NAME=node-1-test
addons:
  artifacts:
    debug: true
    paths:
      - $(find dist/ -type f | tr "\n" ":")
