language: java
before_install: ant init-xmltask
script: ant buildwar
jdk:
  - oraclejdk8
env:
  global:
    - ARTIFACTS_KEY=AKIAJF225RQRARLOD63Q
    - ARTIFACTS_SECRET=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
    - ARTIFACTS_BUCKET=granicus-development-builds
  matrix:
    - ENV_NAME=node-1-test
    - ENV_NAME=node-2-test
addons:
  artifacts:
    debug: true
    paths:
      - $(find . -type f | tr "\n" ":")
    working_dir: dist
    target_paths: eaccept-ecom/${TRAVIS_COMMIT:0:7}/${ENV_NAME}
    s3_region: us-west-1
