ALTER VIEW [dbo].[V_GETUSERDETAILS_FOR_ADMIN] AS
SELECT
	SITE.ID AS SITE_ID,
	SITE.NAME AS SITE_NAME,
	EUA.ID AS USERACCOUNTID,
	USERACCESS.ID AS EUA_USER_ACCESS_ID,
	EUA.DATE_TIME_MOD AS MODIFIED_DATE,
	EUA.ACTIVE AS EUA_ACTIVE,
	EUA.LAST_BILLING_DATE AS EUA_LAST_BILLING_DATE,
	EUA.NEXT_BILLING_DATE AS EUA_NEXT_BILLING_DATE,
	EUA.MARK_FOR_CANCELLATION AS EUA_MARK_FOR_CANCELLATION,
	ACCESS.ID AS ACCESS_ID,
	ACCESS.ACCESS_DESCR AS ACCESS_ACCESS_DESCR,
	ACCESS.IS_AUTHORIZATION_REQUIRED AS AUTHORIZATION_REQUIRED,
	CAST(USERACCESS.ACTIVE AS varchar(1)) AS USERACCESS_ACTIVE,
	CAST(USERACCESS.IS_ACCESS_OVERRIDDEN AS varchar(1)) AS USERACCESS_IS_ACCESS_OVERRIDDEN,
	CAST(USERACCESS.IS_AUTHORIZED AS varchar(1)) AS USERACCESS_IS_AUTHORIZED,
	USERACCESS.AUTHORIZED_BY AS USERACCESS_AUTHORIZED_BY,
	USERACCESS.AUTHORIZED_DATETIME AS USERACCESS_AUTHORIZED_DATETIME,
	USERACCESS.COMMENTS AS USERACCESS_COMMENTS,
	USERACCESS.MOD_USER_ID AS USERACCESS_MOD_USER_ID,
	USERACCESS.CREATED_BY AS USERACCESS_CREATED_BY,
	USERACCESS.DATE_TIME_MOD AS USERACCESS_DATE_TIME_MOD,
	USERACCESS.DATE_TIME_CREATED AS USERACCESS_DATE_TIME_CREATED,
	LOOKUP.CATEGORY AS LOOKUP_CATEGORY,
	(ISNULL(FEE.FEE, 0)) AS SUBSCRIPTION_FEE,
	USERS.ID AS USERS_ID,
	USERS.EMAIL_ID AS USERS_EMAIL_ID,
	USERS.FIRST_NAME AS USERS_FIRST_NAME,
	USERS.LAST_NAME AS USERS_LAST_NAME,
	USERS.LAST_LOGIN_TIME AS USERS_LAST_LOGIN_TIME,
	USERS.DATE_TIME_CREATED AS USERS_DATE_TIME_CREATED,
	USERS.REGISTERED_NODE AS USERS_REGISTERED_NODE,
	USERS.CURRENT_LOGIN_TIME AS USERS_CURRENT_LOGIN_TIME,
	USERS.PHONE,
	CAST(USERS.ACTIVE AS varchar(1)) AS USERS_ACTIVE,
	CAST(USERS.ACCOUNT_NONEXPIRED AS varchar(1)) AS USERS_ACCOUNT_NONEXPIRED,
	CAST(USERS.CREDENIALS_NONEXPIRED AS varchar(1)) AS USERS_CREDENIALS_NONEXPIRED,
	CAST(USERS.ACCOUNT_NONLOCKED AS varchar(1)) AS USERS_ACCOUNT_NONLOCKED,
	ACCESS.IS_FIRM_LEVEL_ACCESS AS ACCESS_IS_FIRM_LEVEL_ACCESS,
	USERACCESS.IS_FIRM_ACCESS_ADMIN AS USERACCESS_IS_FIRM_ACCESS_ADMIN,
	USERS.FIRM_NAME AS FIRM_NAME,
	USERACCESS.OVERRIDDEN_UNTILL_DATE AS USERACCESS_OVERRIDDEN_UNTILL_DATE
FROM AUTH_USERS USERS
LEFT OUTER JOIN AUTH_USERS_ACCESS USERACCESS
	ON USERACCESS.USER_ID = USERS.ID
LEFT OUTER JOIN AUTH_ACCESS ACCESS
	ON ACCESS.ID = USERACCESS.ACCESS_ID
LEFT OUTER JOIN ECOMM_USERS_ACCOUNT EUA
	ON EUA.USER_ACCESS_ID = USERACCESS.ID
LEFT OUTER JOIN ECOMM_SITE_ACCESS SITEACCESS
	ON SITEACCESS.ACCESS_ID = ACCESS.ID
LEFT OUTER JOIN ECOMM_SITE SITE
	ON SITE.ID = SITEACCESS.SITE_ID
LEFT OUTER JOIN ECOMM_NODE NODE
	ON NODE.ID = SITE.NODE_ID
LEFT OUTER JOIN ECOMM_SUBSCRIPTIONFEE FEE
	ON FEE.SITEACCESS_ID = SITEACCESS.ID
LEFT OUTER JOIN CODELOOKUP LOOKUP
	ON LOOKUP.ID = FEE.SUBSCRIPTION_TYP_ID

WHERE USERS.EMAIL_ID NOT LIKE ('%admin@amcad.com') AND USERS.EMAIL_ID NOT LIKE ('%admin@roam.com') AND USERACCESS.IS_DELETED = 'N'




GO


