CREATE TABLE dbo.ACTIVE_JOB
(
  ID int IDENTITY(1,1) PRIMARY KEY,
  JOB_NAME varchar(250) NOT NULL,
  HOST_NAME varchar(100) NOT NULL,
  DATE_TIME_CREATED datetime NOT NULL DEFAULT GETDATE(),
  DATE_TIME_MOD datetime NOT NULL DEFAULT GETDATE(),
  MOD_USER_ID varchar(50) NOT NULL DEFAULT 'SYSTEM',
  ACTIVE char(1) NOT NULL DEFAULT 'Y',
  CREATED_BY varchar(50) NOT NULL DEFAULT 'SYSTEM'
)
