/****** Object:  View [dbo].[V_GET_PAYASUGO_TX_INCLUDE_FIRM_USERS]    Script Date: 9/17/2015 9:47:06 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[V_GET_PAYASUGO_TX_INCLUDE_FIRM_USERS] AS
(
SELECT DISTINCT
  COALESCE(CAST(items.ID AS VARCHAR), payAsUGoTx.TX_REFERENCE_NUM) AS ID,
  payAsUGoTx.ID AS PAYASUGO_TRANSACTION_ID,
  payAsUGoTx.TX_REFERENCE_NUM AS TX_REFERENCE_NUM,
  CASE payAsUGoTx.TX_TYPE
    WHEN 'CHARGE' THEN payAsUGoTx.TX_AMOUNT
    WHEN 'REFUND' THEN 0 - payAsUGoTx.TX_AMOUNT
  END AS TX_AMOUNT,
  payAsUGoTx.TX_DATE AS TX_DATE,
  payAsUGoTx.CARD_NUMBER AS CARD_NUMBER,
  payAsUGoTx.ACCOUNTNAME AS ACCOUNTNAME,
  payAsUGoTx.TX_TYPE AS TX_TYPE,
  payAsUGoTx.IS_CERTIFIED AS IS_CERTIFIED,
  payAsUGoTx.DATE_TIME_CREATED AS DATE_TIME_CREATED,
  site.NAME AS SITE_NAME,
  payAsUGoTx.ITEM_COUNT AS ITEMSPURCHASED, 
  payAsUGoTx.CREATED_BY AS CREATED_BY,
  site.DESCRIPTION AS SITE_DESCRIPTION,
  site.TIMEZONE AS SITE_TIMEZONE,
  transactionUser.EMAIL_ID AS USERNAME,
  AA.ACCESS_DESCR AS SUBSCRIPTION,
  node.NAME AS NODE_NAME,
  transactionUser.EMAIL_ID AS FIRM_USERNAME,
  payAsUGoTx.COMMENTS AS TX_COMMENTS,
  items.COMMENTS AS ITEM_COMMENTS
FROM ECOMM_PAYASUGO_TX payAsUGoTx
LEFT JOIN ECOMM_PAYASUGO_TX_ITEMS items
ON payAsUGoTx.ID = items.PAYASUGO_TX_ID
INNER JOIN AUTH_USERS transactionUser
ON payAsUGoTx.USER_ID = transactionUser.ID
INNER JOIN ECOMM_MERCHANTINFO merchant
ON payAsUGoTx.MERCHANT_ID = merchant.ID
INNER JOIN AUTH_ACCESS AA
ON payAsUGoTx.ACCESS_ID = AA.ID
INNER JOIN ECOMM_SITE site
ON site.ID = merchant.SITE_ID
INNER JOIN ECOMM_NODE node
ON node.ID = site.NODE_ID
WHERE payAsUGoTx.FIRM_ADMIN_USER_ACCESS_ID IS NULL
)
UNION
(
SELECT DISTINCT
  COALESCE (CAST(items.ID AS VARCHAR), payAsUGoTx.TX_REFERENCE_NUM) AS ID,
  payAsUGoTx.ID AS PAYASUGO_TRANSACTION_ID,
  payAsUGoTx.TX_REFERENCE_NUM AS TX_REFERENCE_NUM,
  CASE payAsUGoTx.TX_TYPE
    WHEN 'CHARGE' THEN payAsUGoTx.TX_AMOUNT
    WHEN 'REFUND' THEN 0 - payAsUGoTx.TX_AMOUNT
  END AS TX_AMOUNT,
  payAsUGoTx.TX_DATE AS TX_DATE,
  payAsUGoTx.CARD_NUMBER AS CARD_NUMBER,
  payAsUGoTx.ACCOUNTNAME AS ACCOUNTNAME,
  payAsUGoTx.TX_TYPE AS TX_TYPE,
  payAsUGoTx.IS_CERTIFIED AS IS_CERTIFIED,
  payAsUGoTx.DATE_TIME_CREATED AS DATE_TIME_CREATED,
  site.NAME AS SITE_NAME,
  payAsUGoTx.ITEM_COUNT AS ITEMSPURCHASED,
  payAsUGoTx.CREATED_BY AS CREATED_BY,
  site.DESCRIPTION AS SITE_DESCRIPTION,
  site.TIMEZONE AS SITE_TIMEZONE,
  transactionUser.EMAIL_ID AS USERNAME,
  AA.ACCESS_DESCR AS SUBSCRIPTION,
  node.NAME AS NODE_NAME,
  firmUser.EMAIL_ID AS FIRM_USERNAME,
  payAsUGoTx.COMMENTS AS TX_COMMENTS,
  items.COMMENTS AS ITEM_COMMENTS
FROM ECOMM_PAYASUGO_TX payAsUGoTx
LEFT JOIN ECOMM_PAYASUGO_TX_ITEMS items
ON payAsUGoTx.ID = items.PAYASUGO_TX_ID
INNER JOIN AUTH_USERS transactionUser
ON payAsUGoTx.USER_ID = transactionUser.ID
INNER JOIN ECOMM_MERCHANTINFO merchant
ON payAsUGoTx.MERCHANT_ID = merchant.ID
INNER JOIN AUTH_ACCESS AA
ON payAsUGoTx.ACCESS_ID = AA.ID
INNER JOIN ECOMM_SITE site
ON site.ID = merchant.SITE_ID
INNER JOIN ECOMM_NODE node
ON node.ID = site.NODE_ID
INNER JOIN AUTH_USERS_ACCESS firmUserAccess
ON (
  firmUserAccess.FIRM_ADMIN_USER_ACCESS_ID = payAsUGoTx.FIRM_ADMIN_USER_ACCESS_ID OR
  firmUserAccess.ID = payAsUGoTx.FIRM_ADMIN_USER_ACCESS_ID
)
INNER JOIN AUTH_USERS firmUser ON
firmUserAccess.USER_ID = firmUser.ID 
WHERE payAsUGoTx.FIRM_ADMIN_USER_ACCESS_ID IS NOT NULL
  AND firmUserAccess.IS_DELETED = 'N'
)

GO
